<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateFormatosTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('formatos', function (Blueprint $table) {
            $table->increments('idM');
            $table->string('sistemadesaludM',50);
            $table->string('epsM',50)->nullable();
            $table->string('arlM',50)->nullable();
            $table->string('eps1M',100);
            $table->string('arl1M',100);
            $table->string('sisbenM',50)->nullable();
            $table->string('SaludcolmenaM',50)->nullable();
            $table->string('bonsaludenliquidaciónM',50)->nullable();
            $table->string('institutodesegurossocialesepsM',50)->nullable();
            $table->string('unimeceM',50)->nullable();
            $table->string('compensareM',50)->nullable();
            $table->string('epsprogrcomfenalcoantioquiaM',50)->nullable();
            $table->string('susaludepsM',50)->nullable();
            $table->string('colsegurosM',50)->nullable();
            $table->string('comfenalcovalleM',50)->nullable();
            $table->string('saludcoopM',50)->nullable();
            $table->string('humanavivirsM',50)->nullable();
            $table->string('saludcolpatriaM',50)->nullable();
            $table->string('epsserviciooccidentaldesaludM',50)->nullable();
            $table->string('epsrisaraldaltdaenliquidaciónM',50)->nullable();
            $table->string('caprecomepsM',50)->nullable();
            $table->string('corporanonimasenliquidaciónM',50)->nullable();
            $table->string('epsconvidaM',50)->nullable();
            $table->string('cajanalepsM',50)->nullable();
            $table->string('capresocaepsM',50)->nullable();
            $table->string('solsaludepsM',50)->nullable();
            $table->string('barranquillasanaepsenliquidaciónM',50)->nullable();
            $table->string('calisaludepsM',50)->nullable();
            $table->string('epsdecaldasM',50)->nullable();
            $table->string('coosaludM',50)->nullable();
            $table->string('epscondorM',50)->nullable();
            $table->string('selvasaludepsM',50)->nullable();
            $table->string('metropolitanadesaludepsenliquidaciónM',50)->nullable();
            $table->string('riesgosprofecolmesacompdesegudevidaM',50)->nullable();
            $table->string('laequidadsegdevidaorgancooplaequividaM',50)->nullable();
            $table->string('segurosdevidacolpatriaM',50)->nullable();
            $table->string('AmbuqM',50)->nullable();
            $table->string('cajacopiM',50)->nullable();
            $table->string('comfacorM',50)->nullable();
            $table->string('comfasucreM',50)->nullable();
            $table->string('compartaM',50)->nullable();
            $table->string('emdisaludM',50)->nullable();
            $table->string('mutualserM',50)->nullable();
            $table->string('mapfreM',50)->nullable();
            $table->string('nuevaepssubsidiadaM',50)->nullable();
            $table->string('saludvidaM',50)->nullable();
            $table->string('cafesaludM',50)->nullable();
            $table->string('coomevaM',50)->nullable();
            $table->string('nuevaepscontributivoM',50)->nullable();
            $table->string('saludtotalM',50)->nullable();
            $table->string('epssanitasM',50)->nullable();
            $table->string('epssuraM',50)->nullable();
            $table->string('aliansaludM',50)->nullable();
            $table->string('cruzblancaM',50)->nullable();
            $table->string('sanitasM',50)->nullable();
            $table->string('famisanarM',50)->nullable();
            $table->string('segurosdevidaalfasaM',50)->nullable();
            $table->string('libertysegurosdevidaM',50)->nullable();
            $table->string('positivacompañiadesegurosM',50)->nullable();
            $table->string('arpsuraM',50)->nullable();
            $table->string('arpalfaM',50)->nullable();
            $table->string('SuraM',50)->nullable();
            $table->string('fondodesolidaridadygarantíafosygaM',50)->nullable();
            $table->string('capitalsaludM',50)->nullable();
            $table->string('CooperativadeSaludComunitariaCompartaM',50)->nullable();
            $table->string('EntidadCooperativaSolidariadeSaludEcoopsosM',50)->nullable();
            $table->string('AsociaciónMutualLaEsperanzaAsmetSaludM',50)->nullable();
            $table->string('ComfaboyM',50)->nullable();
            $table->string('ciadesegurosbolivarsaM',50)->nullable();
            $table->string('compañiadesegurosdevidaauroraM',50)->nullable();
            $table->string('tallaM',50);
            $table->string('xxsM',50)->nullable();
            $table->string('xsM',50)->nullable();
            $table->string('sM',50)->nullable();
            $table->string('mM',50)->nullable();
            $table->string('lM',50)->nullable();
            $table->string('xlM',50)->nullable();
            $table->string('xxlM',50)->nullable();
            $table->string('pesoM',50);
            $table->string('frecuenciacardiacaM',50);
            $table->string('frecuenciarespiratoriaM',50);
            $table->string('enfermedadcongénitasM',50)->nullable();
            $table->string('paperasM',50)->nullable();
            $table->string('enfermedadesdelasangreM',50)->nullable();
            $table->string('traumatismosM',50)->nullable();
            $table->string('sarampiónM',50)->nullable();
            $table->string('enfermedadesdegangliosM',50)->nullable();
            $table->string('operacionesM',50)->nullable();
            $table->string('enfermedaddigestivasM',50)->nullable();
            $table->string('enfermedadesdelavistaM',50)->nullable();
            $table->string('golpesfuertesM',50)->nullable();
            $table->string('hepatitisenfermedaddelhígadoM',50)->nullable();
            $table->string('enfermedadesglandularesM',50)->nullable();
            $table->string('lesionesarticularesM',50)->nullable();
            $table->string('enfermedadesrenalesM',50)->nullable();
            $table->string('intervencionesquirúrgicasM',50)->nullable();
            $table->string('fracturasengincesM',50)->nullable();
            $table->string('infeccionesurinariasM',50)->nullable();
            $table->string('heridasM',50)->nullable();
            $table->string('enfermedaddeloshuesosM',50)->nullable();
            $table->string('enfermedadesdegenitalesM',50)->nullable();
            $table->string('enfermedadesdelapielM',50)->nullable();
            $table->string('enfermedadesmuscularesM',50)->nullable();
            $table->string('enfermedadesneurológicasM',50)->nullable();
            $table->string('enfermedadesauditivasM',50)->nullable();
            $table->string('fiebrereumáticaM',50)->nullable();
            $table->string('dolordeCabezamareosM',50)->nullable();
            $table->string('enfermedadescrónicasM',50)->nullable();
            $table->string('artritisartrosisM',50)->nullable();
            $table->string('convulsionesepilepsiaM',50)->nullable();
            $table->string('psoriasisM',50)->nullable();
            $table->string('enfermedadesrespiratoriasM',50)->nullable();
            $table->string('perdidadelconocimientoM',50)->nullable();
            $table->string('consumodealcoholM',50)->nullable();
            $table->string('enfermedadesarticularesM',50)->nullable();
            $table->string('deshidrataciónM',50)->nullable();
            $table->string('consumodetabacoM',50)->nullable();
            $table->string('sinusitisotitisanginasM',50)->nullable();
            $table->string('enfermedadespsiquiátricasM',50)->nullable();
            $table->string('enfTransmisiónsexualM',50)->nullable();
            $table->string('asmaM',50)->nullable();
            $table->string('diabetesM',50)->nullable();
            $table->string('transfusionesM',50)->nullable();
            $table->string('neumoníabronconeumoníaM',50)->nullable();
            $table->string('chagasM',50)->nullable();
            $table->string('hemodiálisisM',50)->nullable();
            $table->string('varicelaM',50)->nullable();
            $table->string('soplosencorazónM',50)->nullable();
            $table->string('hipertensiónarterialM',50)->nullable();
            $table->string('rubeolaM',50)->nullable();
            $table->string('enfermedadescardiacasM',50)->nullable();
            $table->string('hipoglicemiaM',50)->nullable();
            $table->string('alérgicoaalgunapicaduradeinsectoM',50)->nullable();
            $table->string('alérgicoaalgúnmedicamentoM',50)->nullable();
            $table->string('alérgicoaalgúnalimentoM',50)->nullable();
            $table->string('tomaalgunamedicaciónM',50)->nullable();
            $table->string('tipodesangreM',50);
            $table->string('a+M',50)->nullable();
            $table->string('a-M',50)->nullable();
            $table->string('b+M',50)->nullable();
            $table->string('b-M',50)->nullable();
            $table->string('o+M',50)->nullable();
            $table->string('o-M',50)->nullable();
            $table->string('ab+M',50)->nullable();
            $table->string('ab-M',50)->nullable();
            $table->string('observacionesM',200)->nullable();


            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('formatos');
    }
}